console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  muted = '#AAAAAA'
  primary = '#0099FF'
  secondary = '#FFFF1A'
  vibrant = '#66FF33'

[transient_prompt]
  foreground = 'primary'
  background = 'transparent'
  foreground_templates = ['{{ if gt .Code 0 }}red{{end}}', '{{ if eq .Code 0 }}p:muted{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = '#26C6DA'
    background = 'transparent'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'p:vibrant'
    background = 'transparent'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .Shell }}  {{ path .Path .Location }} '
    foreground = 'p:primary'
    background = 'transparent'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:vibrant>{{ if gt .Behind 0 }}↓{{ end }}{{ if gt .Ahead 0 }}↓{{ end }}</>'
    foreground = 'p:muted'
    powerline_symbol = ''
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:muted'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'
      threshold = 3000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if .Env.TMUX }}tmux {{ end }}❯'
    foreground = 'p:muted'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}red{{end}}', '{{ if eq .Code 0 }}p:muted{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' '
    foreground = 'transparent'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
