version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
type = "prompt"
alignment = "left"

    [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "#26C6DA"
    background = "transparent"
    template = "{{.Icon}} "

    [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "p:vibrant"
    background = "transparent"
    template = "{{ if .SSHSession }} {{ end }}{{ .UserName }} "

    [[blocks.segments]]
    type = "path"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    template = "{{ .Shell }}  {{ path .Path .Location }} "
    foreground = "p:primary"
    background = "transparent"

        [blocks.segments.properties]
        style = "full"

        [[blocks.segments]]
        type = "git"
        style = "plain"
        powerline_symbol = ""
        foreground = "p:muted"
        background = "transparent"
        template = "{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:vibrant>{{ if gt .Behind 0 }}↓{{ end }}{{ if gt .Ahead 0 }}↓{{ end }}</>"

            [blocks.segments.properties]
            branch_icon = ""
            commit_icon = "@"
            fetch_status = true

            [properties]
            fetch_status = true
            fetch_upstream_icon = true
            source = "cli"

[[blocks]]
type = "rprompt"
overflow = "hidden"

    [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:muted"
    background = "transparent"
    template = "{{ .FormattedMs }}"

    [blocks.segments.properties]
    threshold = 3000
    style = "austin"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

    [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:muted"
    background = "transparent"
    template = "{{ if .Env.TMUX }}tmux {{ end }}❯"
    foreground_templates = [
        "{{ if gt .Code 0 }}red{{end}}",
        "{{ if eq .Code 0 }}p:muted{{end}}",
    ]

    [[blocks.segments]]
    type = "text"
    style = "plain"
    template = " "
    foreground = "transparent"
    background = "transparent"

[transient_prompt]
foreground = "primary"
background = "transparent"
foreground_templates = [
    "{{ if gt .Code 0 }}red{{end}}",
    "{{ if eq .Code 0 }}p:muted{{end}}",
]

[palette] 
primary = "#0099FF"
secondary = "#FFFF1A"
vibrant = "#66FF33"
muted = "#AAAAAA"
